In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv("datasets/student_multiple_features.csv")
data

   Student  StudyHours Attendance  PreviousMarks  FinalMarks
0    Aarav           2         70           38.0          42
1     Sita           3         75           45.0          50
2      Ram           4         80           52.0          58
3   Anisha           5         85           60.0          68
4    Rohan           6         90           68.0          78
5    Priya           7         92           75.0          85
6    Kiran           8         95           82.0          92
7    Nabin           4         78           55.0          60
8    Suman           5         82           63.0          70
9   Alisha           6         88           70.0          79
10  Bikash           7         91           78.0          87
11  Sabina           8         96           85.0          95
12  Roshan           3         72           48.0          52
13    Puja           9         98           90.0          98
14  Manish           5         86           66.0          73
15  Aakash           6     Absent           72.0          81
16    Rita           4         79           58.0          61
17   Deepa           7         90            NaN          89
18  Sanjay           8         97           88.0          96
19  Kushal           5         84           64.0          74

In [3]:
data.head(5)

  Student  StudyHours Attendance  PreviousMarks  FinalMarks
0   Aarav           2         70           38.0          42
1    Sita           3         75           45.0          50
2     Ram           4         80           52.0          58
3  Anisha           5         85           60.0          68
4   Rohan           6         90           68.0          78

In [4]:
data.tail(5)

   Student  StudyHours Attendance  PreviousMarks  FinalMarks
15  Aakash           6     Absent           72.0          81
16    Rita           4         79           58.0          61
17   Deepa           7         90            NaN          89
18  Sanjay           8         97           88.0          96
19  Kushal           5         84           64.0          74

In [7]:
data.shape

(20, 5)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student        20 non-null     str
 1   StudyHours     20 non-null     int64
 2   Attendance     20 non-null     str
 3   PreviousMarks  19 non-null     float64
 4   FinalMarks     20 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 932.0 bytes

In [6]:
data.describe()

       StudyHours  PreviousMarks  FinalMarks
count   20.000000      19.000000   20.000000
mean     5.600000      66.157895   74.400000
std      1.930367      14.788371   16.519207
min      2.000000      38.000000   42.000000
25%      4.000000      56.500000   60.750000
50%      5.500000      66.000000   76.000000
75%      7.000000      76.500000   87.500000
max      9.000000      90.000000   98.000000

In [10]:
data.isna().sum()

Student          0
StudyHours       0
Attendance       0
PreviousMarks    1
FinalMarks       0
dtype: int64

In [12]:
data['PreviousMarks']=data['PreviousMarks'].fillna(data['PreviousMarks'].quantile(0.5))

In [13]:
data.isna().sum()

Student          0
StudyHours       0
Attendance       0
PreviousMarks    0
FinalMarks       0
dtype: int64

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student        20 non-null     str
 1   StudyHours     20 non-null     int64
 2   Attendance     20 non-null     str
 3   PreviousMarks  20 non-null     float64
 4   FinalMarks     20 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 932.0 bytes

In [17]:
numericd=['StudyHours',"Attendance",'PreviousMarks','FinalMarks']

In [21]:
for c in numericd:
    data[c]=pd.to_numeric(data[c],errors="coerce")
    data[c]=data[c].fillna(data[c].quantile(0.5))

In [22]:
data

   Student  StudyHours  Attendance  PreviousMarks  FinalMarks
0    Aarav           2        70.0           38.0          42
1     Sita           3        75.0           45.0          50
2      Ram           4        80.0           52.0          58
3   Anisha           5        85.0           60.0          68
4    Rohan           6        90.0           68.0          78
5    Priya           7        92.0           75.0          85
6    Kiran           8        95.0           82.0          92
7    Nabin           4        78.0           55.0          60
8    Suman           5        82.0           63.0          70
9   Alisha           6        88.0           70.0          79
10  Bikash           7        91.0           78.0          87
11  Sabina           8        96.0           85.0          95
12  Roshan           3        72.0           48.0          52
13    Puja           9        98.0           90.0          98
14  Manish           5        86.0           66.0          73
15  Aakash           6        86.0           72.0          81
16    Rita           4        79.0           58.0          61
17   Deepa           7        90.0           66.0          89
18  Sanjay           8        97.0           88.0          96
19  Kushal           5        84.0           64.0          74

In [36]:
X=data[['StudyHours', 'Attendance', 'PreviousMarks']]
X=X.to_numpy()
X.shape

(20, 3)

In [37]:
Y=data["FinalMarks"]
Y.to_numpy()
Y.shape

(20,)

In [38]:
from sklearn.model_selection import train_test_split
f_train,f_test,l_train,_test=train_test_split(X,Y,test_size=0.2, random_state=42)

In [39]:
model=LinearRegression()
model.fit(f_train,l_train)

LinearRegression()

In [40]:
print("bias or y when x=0 is",model.intercept_)

bias or y when x=0 is -24.726565343333647

In [41]:
print("Coefficient of StudyHours:", model.coef_[0])
print("Coefficient of Attendance:", model.coef_[1])
print("Coefficient of PreviousMarks:", model.coef_[2])

Coefficient of StudyHours: 0.46955085570045013
Coefficient of Attendance: 0.5471098161324163
Coefficient of PreviousMarks: 0.7398940936343379

In [42]:
arr=np.array([
    [5,90,70],
    [7,95,82],
    [3,75,55]
])
arr

array([[ 5, 90, 70],
       [ 7, 95, 82],
       [ 3, 75, 55]])

In [43]:
predictions=model.predict(arr)
print(predictions)

[78.65365894 91.20703886 58.40949858]

In [45]:
students = ['1', '2', '3']
for s, p in zip(students, predictions):
    print(f"Student {s} =>Predicted Final Marks: {p:.2f}")

Student 1 =>Predicted Final Marks: 78.65
Student 2 =>Predicted Final Marks: 91.21
Student 3 =>Predicted Final Marks: 58.41