In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("datasets/LMS_Dirty_Dataset.csv")
d

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [3]:
d.head(10)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed

In [4]:
d.tail(10)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
340,341,Hari,Digital Marketing,Biratnagar,31,Female,2026-06-10,5000,20,Pending,96.0,38,71,5,Ishan,9831430348,user340@gmail.com,Ongoing
341,342,Gita,Flutter,Biratnagar,32,Female,2026-04-16,5000,10,Paid,54.0,33,61,5,Ishan,9865928299,user341@gmail.com,Ongoing
342,343,Aarav,UI/UX,Itahari,18,Male,2026-03-01,7000,10,Paid,45.0,85,46,5,Manish,9832055006,user342@gmail.com,Completed
343,344,Gita,Python with AI/ML,Kathmandu,33,Male,2026-05-07,5000,20,Paid,67.0,57,30,4,Samriddha,9828498406,user343@gmail.com,Ongoing
344,345,Gita,Digital Marketing,Pokhara,29,Male,2026-05-18,10000,10,Paid,71.0,45,89,4,Manish,9847970014,user344@gmail.com,Completed
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [5]:
d.shape

(350, 18)

In [6]:
d.columns

Index(['student_id', 'student_name', 'course', 'city', 'age', 'gender',
       'enrollment_date', 'course_fee', 'discount', 'payment_status',
       'attendance_percent', 'assignment_score', 'final_score', 'rating',
       'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [7]:
d.dtypes

student_id              int64
student_name              str
course                    str
city                      str
age                     int64
gender                    str
enrollment_date           str
course_fee              int64
discount                int64
payment_status            str
attendance_percent    float64
assignment_score        int64
final_score             int64
rating                  int64
mentor                    str
phone                     str
email                     str
completion_status         str
dtype: object

In [8]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          350 non-null    int64
 1   student_name        350 non-null    str
 2   course              350 non-null    str
 3   city                350 non-null    str
 4   age                 350 non-null    int64
 5   gender              350 non-null    str
 6   enrollment_date     350 non-null    str
 7   course_fee          350 non-null    int64
 8   discount            350 non-null    int64
 9   payment_status      350 non-null    str
 10  attendance_percent  349 non-null    float64
 11  assignment_score    350 non-null    int64
 12  final_score         350 non-null    int64
 13  rating              350 non-null    int64
 14  mentor              350 non-null    str
 15  phone               350 non-null    str
 16  email               350 non-null    str
 17  completion_status   350 non-null    str
dtypes: float64(1), int64(7), str(10)
memory usage: 49.3 KB

In [9]:
d.describe()

,student_id,age,course_fee,discount,attendance_percent,assignment_score,final_score,rating
count,350.000000,350.000000,350.000000,350.000000,349.000000,350.000000,350.000000,350.000000
mean,175.500000,26.174286,10085.711429,9.600000,70.154728,67.011429,65.011429,3.960000
std,101.180532,5.485686,53109.214627,7.929489,16.697929,20.686773,20.556718,0.817852
min,1.000000,17.000000,-5000.000000,0.000000,40.000000,-5.000000,30.000000,3.000000
25%,88.250000,21.000000,5000.000000,0.000000,58.000000,51.000000,47.000000,3.000000
50%,175.500000,27.000000,7000.000000,10.000000,70.000000,69.000000,65.000000,4.000000
75%,262.750000,31.000000,10000.000000,20.000000,83.000000,85.750000,82.000000,5.000000
max,350.000000,35.000000,999999.000000,20.000000,100.000000,100.000000,100.000000,5.000000

In [10]:
d.duplicated().sum()

np.int64(0)

In [11]:
d.duplicated(subset="student_id").sum()

np.int64(0)

In [12]:
d.isnull().sum()

student_id            0
student_name          0
course                0
city                  0
age                   0
gender                0
enrollment_date       0
course_fee            0
discount              0
payment_status        0
attendance_percent    1
assignment_score      0
final_score           0
rating                0
mentor                0
phone                 0
email                 0
completion_status     0
dtype: int64

In [13]:
r=d['attendance_percent'].mean()

In [14]:
d['attendance_percent']=d['attendance_percent'].fillna(r)

In [15]:
d['student_id'].mean() #so id columns has all correct dtype

np.float64(175.5)

In [16]:
columns_num=d.select_dtypes(include="number")#searched in web for this

In [17]:
#columns with numeric datatype

c=columns_num.columns
c

Index(['student_id', 'age', 'course_fee', 'discount', 'attendance_percent',
       'assignment_score', 'final_score', 'rating'],
      dtype='str')

In [18]:
print(type(c))
c=c.drop("student_id")
c

<class 'pandas.Index'>

Index(['age', 'course_fee', 'discount', 'attendance_percent',
       'assignment_score', 'final_score', 'rating'],
      dtype='str')

In [19]:
test=pd.to_numeric(d["age"],errors="coerce")
test.isnull().sum()

np.int64(0)

In [20]:
for columns in c:
    if columns=='attendance_percent':
        d[columns]=d[columns].astype(str).str.replace('%','')
    datas=pd.to_numeric(d[columns],errors="coerce")
    #print(columns,":",datas) for testing if any error with isnull and sum but i removed it
    d[columns]=datas.fillna(datas.mean())

In [21]:
d

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [22]:
columns_str=d.select_dtypes(include="string").columns
columns_str

Index(['student_name', 'course', 'city', 'gender', 'enrollment_date',
       'payment_status', 'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [23]:
columns_str=columns_str.drop('enrollment_date')
columns_str

Index(['student_name', 'course', 'city', 'gender', 'payment_status', 'mentor',
       'phone', 'email', 'completion_status'],
      dtype='str')

In [24]:
for columns in columns_str:
    if columns=='email':
        d[columns]=d[columns].str.strip()
        print(d[columns])
    else:
        d[columns]=d[columns].str.strip().str.lower().str.title()
        print(d[columns])

0        Gita
1       Nabin
2        Gita
3        Gita
4        Gita
        ...
345      Hari
346    Anisha
347      Sita
348    Anisha
349      Hari
Name: student_name, Length: 350, dtype: str
0             Mern Stack
1           Data Science
2             Mern Stack
3      Digital Marketing
4           Data Science
             ...
345                Ui/Ux
346    Digital Marketing
347              Flutter
348                Ui/Ux
349    Python With Ai/Ml
Name: course, Length: 350, dtype: str
0       Kathmandu
1         Itahari
2          Dharan
3         Itahari
4         Itahari
          ...
345        Dharan
346    Biratnagar
347    Biratnagar
348       Itahari
349        Dharan
Name: city, Length: 350, dtype: str
0      Female
1      Female
2      Female
3      Female
4        Male
        ...
345    Female
346    Female
347      Male
348      Male
349    Female
Name: gender, Length: 350, dtype: str
0      Pending
1      Pending
2         Paid
3      Pending
4      Pending
        ...
345       Paid
346       Paid
347       Paid
348       Paid
349    Pending
Name: payment_status, Length: 350, dtype: str
0      Samriddha
1         Manish
2      Samriddha
3         Manish
4          Ishan
         ...
345    Samriddha
346    Samriddha
347    Samriddha
348        Ishan
349       Manish
Name: mentor, Length: 350, dtype: str
0      9839323411
1      9874340113
2      9874168652
3      9864252889
4      9864166467
          ...
345    9873827203
346    9864328504
347    9821459197
348    9862269669
349    9803556080
Name: phone, Length: 350, dtype: str
0        user0@gmail.com
1        user1@gmail.com
2        user2@gmail.com
3        user3@gmail.com
4        user4@gmail.com
             ...
345    user345@gmail.com
346    user346@gmail.com
347    user347@gmail.com
348    user348@gmail.com
349    user349@gmail.com
Name: email, Length: 350, dtype: str
0        Ongoing
1      Completed
2      Completed
3        Ongoing
4        Ongoing
         ...
345      Ongoing
346      Ongoing
347    Completed
348    Completed
349      Ongoing
Name: completion_status, Length: 350, dtype: str

In [25]:
datas3=pd.to_datetime(d['enrollment_date'],errors="coerce")
datas3.isnull().sum()
#if error nan found we can use a specific date using pd.Timestamp

np.int64(0)

In [26]:
for columns in c:
    d.loc[d[columns]<0,columns]=d.loc[d[columns]<0,columns].abs() # i did this coz if i did abs(d[columns]) more memory
    print(d[columns])

0      17
1      29
2      20
3      20
4      19
       ..
345    21
346    31
347    19
348    27
349    19
Name: age, Length: 350, dtype: int64
0      10000
1      10000
2       5000
3       7000
4       5000
       ...
345    10000
346     5000
347     5000
348     5000
349     5000
Name: course_fee, Length: 350, dtype: int64
0      10
1      20
2      20
3       0
4       0
       ..
345    20
346    10
347    20
348    10
349    20
Name: discount, Length: 350, dtype: int64
0       73.0
1       68.0
2       71.0
3       88.0
4      100.0
       ...
345     98.0
346     45.0
347     80.0
348     63.0
349     84.0
Name: attendance_percent, Length: 350, dtype: float64
0      46
1      31
2      31
3      43
4      89
       ..
345    87
346    51
347    89
348    58
349    57
Name: assignment_score, Length: 350, dtype: int64
0      98
1      63
2      99
3      38
4      98
       ..
345    56
346    44
347    39
348    52
349    62
Name: final_score, Length: 350, dtype: int64
0      5
1      3
2      5
3      5
4      5
      ..
345    5
346    3
347    5
348    5
349    3
Name: rating, Length: 350, dtype: int64

In [27]:
#outlier detction in course fee,attendance percentage,assigment score,final score

In [28]:
d.columns

Index(['student_id', 'student_name', 'course', 'city', 'age', 'gender',
       'enrollment_date', 'course_fee', 'discount', 'payment_status',
       'attendance_percent', 'assignment_score', 'final_score', 'rating',
       'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [29]:
outliers_c=['course_fee','attendance_percent','assignment_score', 'final_score']

In [30]:
dataa={}
for columns in outliers_c:
    q1=d[columns].quantile(0.25)
    print(f"q1 for column:{columns}={q1}")
    q3=d[columns].quantile(0.75)
    print(f"q3 for column:{columns}={q3}")
    median=d[columns].quantile(0.5)
    iqr=q3-q1
    print(f"iqr for column:{columns}={iqr}")
    lower=q1-1.5*iqr
    print(f"lower_bound for column:{columns}={lower}")
    upper=q3+1.5*iqr
    print(f"upper_bound for column:{columns}={upper}")
    print()
    dataa[columns]={
        "q1":q1,
        "q3":q3,
        "iqr":iqr,
        "lower_bound":lower,
        "upper_bound":upper,
        "median":median
        
    }

q1 for column:course_fee=5000.0
q3 for column:course_fee=10000.0
iqr for column:course_fee=5000.0
lower_bound for column:course_fee=-2500.0
upper_bound for column:course_fee=17500.0

q1 for column:attendance_percent=58.0
q3 for column:attendance_percent=83.0
iqr for column:attendance_percent=25.0
lower_bound for column:attendance_percent=20.5
upper_bound for column:attendance_percent=120.5

q1 for column:assignment_score=51.0
q3 for column:assignment_score=85.75
iqr for column:assignment_score=34.75
lower_bound for column:assignment_score=-1.125
upper_bound for column:assignment_score=137.875

q1 for column:final_score=47.0
q3 for column:final_score=82.0
iqr for column:final_score=35.0
lower_bound for column:final_score=-5.5
upper_bound for column:final_score=134.5

In [31]:
print(dataa)
print()
print(dataa['course_fee'])
print()

print(dataa['course_fee']['q1'])

{'course_fee': {'q1': np.float64(5000.0), 'q3': np.float64(10000.0), 'iqr': np.float64(5000.0), 'lower_bound': np.float64(-2500.0), 'upper_bound': np.float64(17500.0), 'median': np.float64(7000.0)}, 'attendance_percent': {'q1': np.float64(58.0), 'q3': np.float64(83.0), 'iqr': np.float64(25.0), 'lower_bound': np.float64(20.5), 'upper_bound': np.float64(120.5), 'median': np.float64(70.0)}, 'assignment_score': {'q1': np.float64(51.0), 'q3': np.float64(85.75), 'iqr': np.float64(34.75), 'lower_bound': np.float64(-1.125), 'upper_bound': np.float64(137.875), 'median': np.float64(69.0)}, 'final_score': {'q1': np.float64(47.0), 'q3': np.float64(82.0), 'iqr': np.float64(35.0), 'lower_bound': np.float64(-5.5), 'upper_bound': np.float64(134.5), 'median': np.float64(65.0)}}

{'q1': np.float64(5000.0), 'q3': np.float64(10000.0), 'iqr': np.float64(5000.0), 'lower_bound': np.float64(-2500.0), 'upper_bound': np.float64(17500.0), 'median': np.float64(7000.0)}

5000.0

In [32]:
for columns in outliers_c:
    print(f'removing outlier from {columns} using drop')
    d=d.drop(d.loc[(d[columns]<dataa[columns]['lower_bound'])|(d[columns]>dataa[columns]['upper_bound'])].index)
    print(d[columns])
    print("----"*100)

removing outlier from course_fee using drop
0      10000
1      10000
2       5000
3       7000
4       5000
       ...
345    10000
346     5000
347     5000
348     5000
349     5000
Name: course_fee, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
removing outlier from attendance_percent using drop
0       73.0
1       68.0
2       71.0
3       88.0
4      100.0
       ...
345     98.0
346     45.0
347     80.0
348     63.0
349     84.0
Name: attendance_percent, Length: 349, dtype: float64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
removing outlier from assignment_score using drop
0      46
1      31
2      31
3      43
4      89
       ..
345    87
346    51
347    89
348    58
349    57
Name: assignment_score, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
removing outlier from final_score using drop
0      98
1      63
2      99
3      38
4      98
       ..
345    56
346    44
347    39
348    52
349    62
Name: final_score, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [33]:
import numpy as np

In [34]:
for columns in outliers_c:
    print(f'removing outlier from {columns} using meidan')
    d.loc[(d[columns]<dataa[columns]['lower_bound'])|(d[columns]>dataa[columns]['upper_bound'])]=np.nan
    d[columns]=d[columns].fillna(dataa[columns]['median'])
    print(d[columns])
    print("----"*100)

removing outlier from course_fee using meidan
0      10000
1      10000
2       5000
3       7000
4       5000
       ...
345    10000
346     5000
347     5000
348     5000
349     5000
Name: course_fee, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
removing outlier from attendance_percent using meidan
0       73.0
1       68.0
2       71.0
3       88.0
4      100.0
       ...
345     98.0
346     45.0
347     80.0
348     63.0
349     84.0
Name: attendance_percent, Length: 349, dtype: float64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
removing outlier from assignment_score using meidan
0      46
1      31
2      31
3      43
4      89
       ..
345    87
346    51
347    89
348    58
349    57
Name: assignment_score, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
removing outlier from final_score using meidan
0      98
1      63
2      99
3      38
4      98
       ..
345    56
346    44
347    39
348    52
349    62
Name: final_score, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [35]:
for columns in outliers_c:
    print(f"Clipping outliers in {columns}")

    d[columns] = d[columns].clip(lower=dataa[columns]["lower_bound"],upper=dataa[columns]["upper_bound"]
    )

    print(d[columns])
    print("----" * 100)

Clipping outliers in course_fee
0      10000
1      10000
2       5000
3       7000
4       5000
       ...
345    10000
346     5000
347     5000
348     5000
349     5000
Name: course_fee, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Clipping outliers in attendance_percent
0       73.0
1       68.0
2       71.0
3       88.0
4      100.0
       ...
345     98.0
346     45.0
347     80.0
348     63.0
349     84.0
Name: attendance_percent, Length: 349, dtype: float64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Clipping outliers in assignment_score
0      46
1      31
2      31
3      43
4      89
       ..
345    87
346    51
347    89
348    58
349    57
Name: assignment_score, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Clipping outliers in final_score
0      98
1      63
2      99
3      38
4      98
       ..
345    56
346    44
347    39
348    52
349    62
Name: final_score, Length: 349, dtype: int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [36]:
for columns in outliers_c:
    print(f"Using Z-score for column: {columns}")

    mean = d[columns].mean()
    std = d[columns].std()
    a="zscore-"+columns

    d[a] = (d[columns] - mean) / std

    print("Mean:", mean)
    print("Standard Deviation:", std)

    outliers = d.loc[
        (d[a] > 3) |
        (d[a] < -3)
    ]

    print(outliers)
    print("-" * 50)

Using Z-score for column: course_fee
Mean: 7277.936962750717
Standard Deviation: 2078.9310600250133
Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, zscore-course_fee]
Index: []
--------------------------------------------------
Using Z-score for column: attendance_percent
Mean: 70.23826569568394
Standard Deviation: 16.62441866770524
Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, zscore-course_fee, zscore-attendance_percent]
Index: []
--------------------------------------------------
Using Z-score for column: assignment_score
Mean: 67.01719197707736
Standard Deviation: 20.618865987757058
    student_id student_name        course     city  age  gender  \
38          39       Anisha  Data Science  Itahari   20  Female

   enrollment_date  course_fee  discount payment_status  ...  \
38      2026-01-14       10000        10        Pending  ...

    assignment_score  final_score  rating  mentor       phone  \
38                 5           55       3  Manish  9856058698

               email completion_status zscore-course_fee  \
38  user38@gmail.com           Ongoing          1.309357

    zscore-attendance_percent  zscore-assignment_score
38                  -0.014332                -3.007789

[1 rows x 21 columns]
--------------------------------------------------
Using Z-score for column: final_score
Mean: 65.0515759312321
Standard Deviation: 20.572486902095484
Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, zscore-course_fee, zscore-attendance_percent, zscore-assignment_score, zscore-final_score]
Index: []

[0 rows x 22 columns]
--------------------------------------------------

In [37]:
d.info()

<class 'pandas.DataFrame'>
Index: 349 entries, 0 to 349
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   student_id                 349 non-null    int64
 1   student_name               349 non-null    str
 2   course                     349 non-null    str
 3   city                       349 non-null    str
 4   age                        349 non-null    int64
 5   gender                     349 non-null    str
 6   enrollment_date            349 non-null    str
 7   course_fee                 349 non-null    int64
 8   discount                   349 non-null    int64
 9   payment_status             349 non-null    str
 10  attendance_percent         349 non-null    float64
 11  assignment_score           349 non-null    int64
 12  final_score                349 non-null    int64
 13  rating                     349 non-null    int64
 14  mentor                     349 non-null    str
 15  phone                      349 non-null    str
 16  email                      349 non-null    str
 17  completion_status          349 non-null    str
 18  zscore-course_fee          349 non-null    float64
 19  zscore-attendance_percent  349 non-null    float64
 20  zscore-assignment_score    349 non-null    float64
 21  zscore-final_score         349 non-null    float64
dtypes: float64(5), int64(7), str(10)
memory usage: 62.7 KB

In [42]:
d.groupby("course")
for group,data in d.groupby("course"):
    print(group)
    print(data)

Data Science
     student_id student_name        course        city  age  gender  \
1             2        Nabin  Data Science     Itahari   29  Female
4             5         Gita  Data Science     Itahari   19    Male
5             6       Anisha  Data Science      Dharan   18    Male
16           17         Hari  Data Science   Kathmandu   22    Male
31           32        Suman  Data Science   Kathmandu   19  Female
34           35        Suman  Data Science   Kathmandu   32  Female
38           39       Anisha  Data Science     Itahari   20  Female
46           47         Hari  Data Science   Kathmandu   18  Female
47           48         Sita  Data Science     Pokhara   32    Male
55           56         Sita  Data Science   Kathmandu   30  Female
58           59         Gita  Data Science         Ktm   31  Female
61           62          Ram  Data Science   Kathmandu   20    Male
64           65        Nabin  Data Science  Biratnagar   26    Male
69           70        Aarav  Data Science     Itahari   33    Male
75           76       Anisha  Data Science      Dharan   28  Female
81           82        Suman  Data Science      Dharan   26    Male
88           89          Ram  Data Science   Kathmandu   20  Female
93           94         Gita  Data Science     Pokhara   31  Female
104         105        Aarav  Data Science   Kathmandu   26    Male
118         119        Suman  Data Science     Pokhara   18  Female
124         125        Nabin  Data Science      Dharan   31  Female
136         137         Hari  Data Science     Itahari   28    Male
139         140        Suman  Data Science     Itahari   21    Male
142         143       Anisha  Data Science      Dharan   20    Male
148         149       Anisha  Data Science   Kathmandu   30  Female
154         155         Hari  Data Science     Pokhara   30  Female
157         158         Sita  Data Science     Pokhara   19  Female
167         168        Aarav  Data Science  Biratnagar   21    Male
176         177        Suman  Data Science   Kathmandu   35    Male
180         181         Gita  Data Science      Dharan   17  Female
188         189        Nabin  Data Science     Pokhara   27    Male
196         197       Anisha  Data Science   Kathmandu   29  Female
198         199        Aarav  Data Science     Itahari   29  Female
199         200         Sita  Data Science      Dharan   29  Female
200         201         Sita  Data Science     Itahari   25    Male
201         202        Aarav  Data Science  Biratnagar   34    Male
204         205        Aarav  Data Science  Biratnagar   35  Female
213         214        Suman  Data Science   Kathmandu   24    Male
217         218        Suman  Data Science      Dharan   35    Male
219         220        Nabin  Data Science      Dharan   22    Male
230         231         Gita  Data Science   Kathmandu   34    Male
238         239         Sita  Data Science     Pokhara   26  Female
250         251         Sita  Data Science  Biratnagar   20  Female
251         252         Hari  Data Science     Pokhara   23    Male
258         259        Suman  Data Science     Pokhara   27    Male
261         262         Gita  Data Science      Dharan   30  Female
266         267         Hari  Data Science   Kathmandu   25    Male
282         283        Suman  Data Science     Itahari   28  Female
292         293         Sita  Data Science     Pokhara   18  Female
298         299        Suman  Data Science      Dharan   34    Male
299         300       Anisha  Data Science   Kathmandu   17    Male
306         307        Nabin  Data Science     Itahari   17  Female
308         309        Suman  Data Science     Itahari   24  Female
313         314        Suman  Data Science     Itahari   18  Female
323         324        Nabin  Data Science   Kathmandu   30  Female
324         325         Sita  Data Science     Pokhara   24    Male
325         326         Hari  Data Science      Dharan   32    Male
327         328        Suman  Data Science     Pokhara   26    Male
333         334         Gita  Data Science      Dharan   23    Male
338         339         Hari  Data Science      Dharan   17    Male

    enrollment_date  course_fee  discount payment_status  ...  final_score  \
1        2026-06-29       10000        20        Pending  ...           63
4        2026-05-28        5000         0        Pending  ...           98
5        2026-04-30        7000        10           Paid  ...           70
16       2026-06-13        7000         0        Pending  ...           75
31       2026-05-27       10000        20        Pending  ...           53
34       2026-06-03        5000         0           Paid  ...           88
38       2026-01-14       10000        10        Pending  ...           55
46       2026-04-02       10000        10        Pending  ...           39
47       2026-04-21        7000         0        Pending  ...           83
55       2026-01-22       10000        10        Pending  ...           86
58       2026-04-08        7000         0           Paid  ...           73
61       2026-02-05       10000         0           Paid  ...           50
64       2026-05-24        7000        20        Pending  ...           30
69       2026-03-28       10000        20           Paid  ...           82
75       2026-01-02        5000         0           Paid  ...           76
81       2026-06-12        5000        20        Pending  ...           46
88       2026-01-08        7000         0        Pending  ...           96
93       2026-05-24        7000        20           Paid  ...           96
104      2026-01-16       10000        20           Paid  ...           98
118      2026-04-10        5000         0           Paid  ...           75
124      2026-03-06       10000         0        Pending  ...           82
136      2026-02-08       10000        10           Paid  ...           33
139      2026-02-05        7000         0           Paid  ...           74
142      2026-02-17        7000         0        Pending  ...           96
148      2026-02-11        5000        10           Paid  ...           49
154      2026-06-21        7000         0           Paid  ...           97
157      2026-05-23        5000        20           Paid  ...          100
167      2026-02-02       10000        20        Pending  ...           59
176      2026-02-26       10000        20           Paid  ...           71
180      2026-04-03       10000        10        Pending  ...           51
188      2026-06-11        5000        20           Paid  ...           63
196      2026-06-22        5000         0           Paid  ...           67
198      2026-02-01        7000        10        Pending  ...           39
199      2026-01-26        7000        10        Pending  ...           63
200      2026-02-01        5000        20        Pending  ...           96
201      2026-04-06        5000        20        Pending  ...           80
204      2026-03-16       10000         0        Pending  ...           73
213      2026-01-02        7000        20        Pending  ...           32
217      2026-02-23        5000        20           Paid  ...           77
219      2026-02-10       10000         0           Paid  ...           69
230      2026-04-01        7000         0        Pending  ...           55
238      2026-04-15       10000        10        Pending  ...           58
250      2026-01-19        7000         0        Pending  ...           86
251      2026-02-04        5000        10           Paid  ...           69
258      2026-05-12       10000         0        Pending  ...           31
261      2026-05-24       10000        10           Paid  ...           44
266      2026-05-01        7000        10           Paid  ...           39
282      2026-04-16       10000        10           Paid  ...           94
292      2026-03-16        7000        10        Pending  ...           69
298      2026-01-06        7000        20           Paid  ...           87
299      2026-06-27        7000        10        Pending  ...           78
306      2026-04-03        5000         0        Pending  ...           70
308      2026-04-25        7000        20           Paid  ...           85
313      2026-05-04        5000        10           Paid  ...           33
323      2026-03-02        7000        10        Pending  ...           78
324      2026-05-01        5000        20           Paid  ...           41
325      2026-06-20       10000        20           Paid  ...           35
327      2026-02-13       10000         0        Pending  ...           82
333      2026-04-13       10000        10        Pending  ...           55
338      2026-04-22        5000        10        Pending  ...           93

     rating     mentor       phone              email completion_status  \
1         3     Manish  9874340113    user1@gmail.com         Completed
4         5      Ishan  9864166467    user4@gmail.com           Ongoing
5         4  Samriddha  9838336446    user5@gmail.com         Completed
16        4      Ishan  9822375884   user16@gmail.com         Completed
31        5  Samriddha  9834450458   user31@gmail.com         Completed
34        4     Manish  9831049943   user34@gmail.com         Completed
38        3     Manish  9856058698   user38@gmail.com           Ongoing
46        5     Manish  9888299298   user46@gmail.com           Ongoing
47        3      Ishan  9889751730   user47@gmail.com         Completed
55        3      Ishan  9892978244   user55@gmail.com           Ongoing
58        3      Ishan  9834298228   user58@gmail.com           Ongoing
61        3      Ishan  9861638782   user61@gmail.com         Completed
64        4  Samriddha  9894912752   user64@gmail.com         Completed
69        5      Ishan  9805642165   user69@gmail.com         Completed
75        4      Ishan  9813931759   user75@gmail.com           Ongoing
81        4  Samriddha  9828788111   user81@gmail.com           Ongoing
88        3  Samriddha  9897565902   user88@gmail.com         Completed
93        5     Manish  9885733218   user93@gmail.com         Completed
104       5     Manish  9816102684  user104@gmail.com         Completed
118       3     Manish  9895116756  user118@gmail.com           Ongoing
124       4      Ishan  9855040973  user124@gmail.com         Completed
136       4      Ishan  9842393125  user136@gmail.com         Completed
139       5     Manish  9856959758  user139@gmail.com         Completed
142       4  Samriddha  9880648942  user142@gmail.com         Completed
148       4      Ishan  9889309832  user148@gmail.com         Completed
154       5     Manish  9885152154  user154@gmail.com           Ongoing
157       5     Manish  9832162137  user157@gmail.com           Ongoing
167       4     Manish  9857557021  user167@gmail.com           Ongoing
176       3      Ishan  9890545949  user176@gmail.com         Completed
180       5      Ishan  9871542781  user180@gmail.com           Ongoing
188       4  Samriddha  9880879160  user188@gmail.com           Ongoing
196       4      Ishan  9841367782  user196@gmail.com         Completed
198       5     Manish  9813798072  user198@gmail.com           Ongoing
199       4  Samriddha  9868238283  user199@gmail.com         Completed
200       5     Manish  9860810445  user200@gmail.com         Completed
201       4      Ishan  9873030211  user201@gmail.com         Completed
204       3     Manish  9848630723  user204@gmail.com           Ongoing
213       5     Manish  9840889901  user213@gmail.com           Ongoing
217       5      Ishan  9834551004  user217@gmail.com         Completed
219       4  Samriddha  9806516386  user219@gmail.com           Ongoing
230       5     Manish  9870475942  user230@gmail.com         Completed
238       4     Manish  9854433348  user238@gmail.com           Ongoing
250       3     Manish  9837716287  user250@gmail.com         Completed
251       3      Ishan  9853738211  user251@gmail.com         Completed
258       4     Manish  9800428055  user258@gmail.com           Ongoing
261       5  Samriddha  9804258047  user261@gmail.com         Completed
266       4      Ishan  9863080418  user266@gmail.com         Completed
282       3      Ishan  9837905639  user282@gmail.com           Ongoing
292       3      Ishan  9826303026  user292@gmail.com         Completed
298       3     Manish  9865044701  user298@gmail.com         Completed
299       4  Samriddha  9868962770  user299@gmail.com           Ongoing
306       4     Manish  9825583895  user306@gmail.com           Ongoing
308       4  Samriddha  9820668267  user308@gmail.com         Completed
313       3      Ishan  9850786193  user313@gmail.com           Ongoing
323       5  Samriddha  9814934857  user323@gmail.com           Ongoing
324       4  Samriddha  9834163380  user324@gmail.com         Completed
325       3     Manish  9839860825  user325@gmail.com         Completed
327       5  Samriddha  9863078333  user327@gmail.com           Ongoing
333       5     Manish  9870900500  user333@gmail.com           Ongoing
338       3  Samriddha  9817310408  user338@gmail.com           Ongoing

    zscore-course_fee zscore-attendance_percent  zscore-assignment_score  \
1            1.309357                 -0.134637                -1.746808
4           -1.095725                  1.790242                 1.066150
5           -0.133692                 -0.796315                 0.144664
16          -0.133692                 -0.134637                 0.872153
31           1.309357                 -0.495552                -1.552811
34          -1.095725                 -1.337687                 0.241663
38           1.309357                 -0.014332                -3.007789
46           1.309357                 -0.796315                -1.455812
47          -0.133692                 -0.976772                 1.211648
55           1.309357                  1.309022                 0.435660
58          -0.133692                  0.587193                 1.163149
61           1.309357                 -0.134637                -1.310314
64          -0.133692                  0.827802                -0.631324
69           1.309357                 -0.074485                 0.144664
75          -1.095725                 -0.435400                -0.097832
81          -1.095725                 -1.337687                -0.873821
88          -0.133692                 -0.856467                -0.776822
93          -0.133692                 -0.254942                -0.291829
104          1.309357                 -0.736162                 0.823654
118         -1.095725                  1.008260                 0.726655
124          1.309357                  1.669937                -0.243330
136          1.309357                  1.188717                -0.728323
139         -0.133692                 -1.518144                -1.213316
142         -0.133692                  0.346583                 1.502644
148         -1.095725                 -1.578297                 0.435660
154         -0.133692                 -1.457992                -0.340329
157         -1.095725                  1.790242                -0.534326
167          1.309357                  1.309022                -0.728323
176          1.309357                 -0.014332                 0.775155
180          1.309357                  1.429327                -1.164816
188         -1.095725                 -0.495552                -1.164816
196         -1.095725                  0.827802                 0.920652
198         -0.133692                 -0.134637                 1.551143
199         -0.133692                 -0.736162                -0.485827
200         -1.095725                 -0.976772                 0.435660
201         -1.095725                  0.647345                -1.358813
204          1.309357                 -0.555705                -0.146332
213         -0.133692                 -1.036924                 0.387160
217         -1.095725                  0.226278                -1.019319
219          1.309357                  0.767650                 0.629657
230         -0.133692                 -1.036924                 0.726655
238          1.309357                  1.609785                 1.017651
250         -0.133692                  0.647345                 1.599642
251         -1.095725                 -1.036924                -0.146332
258          1.309357                 -0.014332                -1.601310
261          1.309357                  0.286430                -0.776822
266         -0.133692                  1.669937                 0.920652
282          1.309357                  0.827802                -0.243330
292         -0.133692                 -1.397839                 1.405645
298         -0.133692                 -0.194790                 0.290162
299         -0.133692                  1.128565                -0.000834
306         -1.095725                  0.346583                -0.049333
308         -0.133692                 -1.518144                -1.649809
313         -1.095725                  0.767650                -0.776822
323         -0.133692                 -0.615857                 1.551143
324         -1.095725                 -0.254942                -0.437327
325          1.309357                 -0.315095                -0.146332
327          1.309357                 -1.818907                 1.454144
333          1.309357                 -1.217382                -1.746808
338         -1.095725                 -1.758754                 1.163149

     zscore-final_score
1             -0.099724
4              1.601577
5              0.240536
16             0.483579
31            -0.585810
34             1.115491
38            -0.488593
46            -1.266331
47             0.872448
55             1.018274
58             0.386362
61            -0.731636
64            -1.703808
69             0.823839
75             0.532188
81            -0.926071
88             1.504360
93             1.504360
104            1.601577
118            0.483579
124            0.823839
136           -1.557983
139            0.434970
142            1.504360
148           -0.780245
154            1.552968
157            1.698794
167           -0.294159
176            0.289145
180           -0.683028
188           -0.099724
196            0.094710
198           -1.266331
199           -0.099724
200            1.504360
201            0.726622
204            0.386362
213           -1.606591
217            0.580796
219            0.191927
230           -0.488593
238           -0.342767
250            1.018274
251            0.191927
258           -1.655200
261           -1.023288
266           -1.266331
282            1.407143
292            0.191927
298            1.066882
299            0.629405
306            0.240536
308            0.969665
313           -1.557983
323            0.629405
324           -1.169114
325           -1.460765
327            0.823839
333           -0.488593
338            1.358534

[60 rows x 22 columns]
Digital Marketing
     student_id student_name             course        city  age  gender  \
3             4         Gita  Digital Marketing     Itahari   20  Female
10           11         Hari  Digital Marketing   Kathmandu   29  Female
15           16         Hari  Digital Marketing     Itahari   17  Female
21           22        Nabin  Digital Marketing     Pokhara   19  Female
23           24          Ram  Digital Marketing     Itahari   33    Male
32           33        Nabin  Digital Marketing  Biratnagar   24  Female
52           53         Gita  Digital Marketing     Pokhara   22  Female
70           71          Ram  Digital Marketing     Itahari   26    Male
80           81         Gita  Digital Marketing     Itahari   22    Male
103         104        Nabin  Digital Marketing   Kathmandu   28    Male
111         112         Gita  Digital Marketing   Kathmandu   23  Female

In [44]:
d.groupby("course").get_group("Data Science")

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,...,final_score,rating,mentor,phone,email,completion_status,zscore-course_fee,zscore-attendance_percent,zscore-assignment_score,zscore-final_score
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,...,63,3,Manish,9874340113,user1@gmail.com,Completed,1.309357,-0.134637,-1.746808,-0.099724
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,...,98,5,Ishan,9864166467,user4@gmail.com,Ongoing,-1.095725,1.790242,1.066150,1.601577
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,...,70,4,Samriddha,9838336446,user5@gmail.com,Completed,-0.133692,-0.796315,0.144664,0.240536
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,...,75,4,Ishan,9822375884,user16@gmail.com,Completed,-0.133692,-0.134637,0.872153,0.483579
31,32,Suman,Data Science,Kathmandu,19,Female,2026-05-27,10000,20,Pending,...,53,5,Samriddha,9834450458,user31@gmail.com,Completed,1.309357,-0.495552,-1.552811,-0.585810
34,35,Suman,Data Science,Kathmandu,32,Female,2026-06-03,5000,0,Paid,...,88,4,Manish,9831049943,user34@gmail.com,Completed,-1.095725,-1.337687,0.241663,1.115491
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,...,55,3,Manish,9856058698,user38@gmail.com,Ongoing,1.309357,-0.014332,-3.007789,-0.488593
46,47,Hari,Data Science,Kathmandu,18,Female,2026-04-02,10000,10,Pending,...,39,5,Manish,9888299298,user46@gmail.com,Ongoing,1.309357,-0.796315,-1.455812,-1.266331
47,48,Sita,Data Science,Pokhara,32,Male,2026-04-21,7000,0,Pending,...,83,3,Ishan,9889751730,user47@gmail.com,Completed,-0.133692,-0.976772,1.211648,0.872448
55,56,Sita,Data Science,Kathmandu,30,Female,2026-01-22,10000,10,Pending,...,86,3,Ishan,9892978244,user55@gmail.com,Ongoing,1.309357,1.309022,0.435660,1.018274
58,59,Gita,Data Science,Ktm,31,Female,2026-04-08,7000,0,Paid,...,73,3,Ishan,9834298228,user58@gmail.com,Ongoing,-0.133692,0.587193,1.163149,0.386362
61,62,Ram,Data Science,Kathmandu,20,Male,2026-02-05,10000,0,Paid,...,50,3,Ishan,9861638782,user61@gmail.com,Completed,1.309357,-0.134637,-1.310314,-0.731636
64,65,Nabin,Data Science,Biratnagar,26,Male,2026-05-24,7000,20,Pending,...,30,4,Samriddha,9894912752,user64@gmail.com,Completed,-0.133692,0.827802,-0.631324,-1.703808
69,70,Aarav,Data Science,Itahari,33,Male,2026-03-28,10000,20,Paid,...,82,5,Ishan,9805642165,user69@gmail.com,Completed,1.309357,-0.074485,0.144664,0.823839
75,76,Anisha,Data Science,Dharan,28,Female,2026-01-02,5000,0,Paid,...,76,4,Ishan,9813931759,user75@gmail.com,Ongoing,-1.095725,-0.435400,-0.097832,0.532188
81,82,Suman,Data Science,Dharan,26,Male,2026-06-12,5000,20,Pending,...,46,4,Samriddha,9828788111,user81@gmail.com,Ongoing,-1.095725,-1.337687,-0.873821,-0.926071
88,89,Ram,Data Science,Kathmandu,20,Female,2026-01-08,7000,0,Pending,...,96,3,Samriddha,9897565902,user88@gmail.com,Completed,-0.133692,-0.856467,-0.776822,1.504360
93,94,Gita,Data Science,Pokhara,31,Female,2026-05-24,7000,20,Paid,...,96,5,Manish,9885733218,user93@gmail.com,Completed,-0.133692,-0.254942,-0.291829,1.504360
104,105,Aarav,Data Science,Kathmandu,26,Male,2026-01-16,10000,20,Paid,...,98,5,Manish,9816102684,user104@gmail.com,Completed,1.309357,-0.736162,0.823654,1.601577
118,119,Suman,Data Science,Pokhara,18,Female,2026-04-10,5000,0,Paid,...,75,3,Manish,9895116756,user118@gmail.com,Ongoing,-1.095725,1.008260,0.726655,0.483579
124,125,Nabin,Data Science,Dharan,31,Female,2026-03-06,10000,0,Pending,...,82,4,Ishan,9855040973,user124@gmail.com,Completed,1.309357,1.669937,-0.243330,0.823839
136,137,Hari,Data Science,Itahari,28,Male,2026-02-08,10000,10,Paid,...,33,4,Ishan,9842393125,user136@gmail.com,Completed,1.309357,1.188717,-0.728323,-1.557983
139,140,Suman,Data Science,Itahari,21,Male,2026-02-05,7000,0,Paid,...,74,5,Manish,9856959758,user139@gmail.com,Completed,-0.133692,-1.518144,-1.213316,0.434970
142,143,Anisha,Data Science,Dharan,20,Male,2026-02-17,7000,0,Pending,...,96,4,Samriddha,9880648942,user142@gmail.com,Completed,-0.133692,0.346583,1.502644,1.504360
148,149,Anisha,Data Science,Kathmandu,30,Female,2026-02-11,5000,10,Paid,...,49,4,Ishan,9889309832,user148@gmail.com,Completed,-1.095725,-1.578297,0.435660,-0.780245
154,155,Hari,Data Science,Pokhara,30,Female,2026-06-21,7000,0,Paid,...,97,5,Manish,9885152154,user154@gmail.com,Ongoing,-0.133692,-1.457992,-0.340329,1.552968
157,158,Sita,Data Science,Pokhara,19,Female,2026-05-23,5000,20,Paid,...,100,5,Manish,9832162137,user157@gmail.com,Ongoing,-1.095725,1.790242,-0.534326,1.698794
167,168,Aarav,Data Science,Biratnagar,21,Male,2026-02-02,10000,20,Pending,...,59,4,Manish,9857557021,user167@gmail.com,Ongoing,1.309357,1.309022,-0.728323,-0.294159
176,177,Suman,Data Science,Kathmandu,35,Male,2026-02-26,10000,20,Paid,...,71,3,Ishan,9890545949,user176@gmail.com,Completed,1.309357,-0.014332,0.775155,0.289145
180,181,Gita,Data Science,Dharan,17,Female,2026-04-03,10000,10,Pending,...,51,5,Ishan,9871542781,user180@gmail.com,Ongoing,1.309357,1.429327,-1.164816,-0.683028
188,189,Nabin,Data Science,Pokhara,27,Male,2026-06-11,5000,20,Paid,...,63,4,Samriddha,9880879160,user188@gmail.com,Ongoing,-1.095725,-0.495552,-1.164816,-0.099724
196,197,Anisha,Data Science,Kathmandu,29,Female,2026-06-22,5000,0,Paid,...,67,4,Ishan,9841367782,user196@gmail.com,Completed,-1.095725,0.827802,0.920652,0.094710
198,199,Aarav,Data Science,Itahari,29,Female,2026-02-01,7000,10,Pending,...,39,5,Manish,9813798072,user198@gmail.com,Ongoing,-0.133692,-0.134637,1.551143,-1.266331
199,200,Sita,Data Science,Dharan,29,Female,2026-01-26,7000,10,Pending,...,63,4,Samriddha,9868238283,user199@gmail.com,Completed,-0.133692,-0.736162,-0.485827,-0.099724
200,201,Sita,Data Science,Itahari,25,Male,2026-02-01,5000,20,Pending,...,96,5,Manish,9860810445,user200@gmail.com,Completed,-1.095725,-0.976772,0.435660,1.504360
201,202,Aarav,Data Science,Biratnagar,34,Male,2026-04-06,5000,20,Pending,...,80,4,Ishan,9873030211,user201@gmail.com,Completed,-1.095725,0.647345,-1.358813,0.726622
204,205,Aarav,Data Science,Biratnagar,35,Female,2026-03-16,10000,0,Pending,...,73,3,Manish,9848630723,user204@gmail.com,Ongoing,1.309357,-0.555705,-0.146332,0.386362
213,214,Suman,Data Science,Kathmandu,24,Male,2026-01-02,7000,20,Pending,...,32,5,Manish,9840889901,user213@gmail.com,Ongoing,-0.133692,-1.036924,0.387160,-1.606591
217,218,Suman,Data Science,Dharan,35,Male,2026-02-23,5000,20,Paid,...,77,5,Ishan,9834551004,user217@gmail.com,Completed,-1.095725,0.226278,-1.019319,0.580796
219,220,Nabin,Data Science,Dharan,22,Male,2026-02-10,10000,0,Paid,...,69,4,Samriddha,9806516386,user219@gmail.com,Ongoing,1.309357,0.767650,0.629657,0.191927
230,231,Gita,Data Science,Kathmandu,34,Male,2026-04-01,7000,0,Pending,...,55,5,Manish,9870475942,user230@gmail.com,Completed,-0.133692,-1.036924,0.726655,-0.488593
238,239,Sita,Data Science,Pokhara,26,Female,2026-04-15,10000,10,Pending,...,58,4,Manish,9854433348,user238@gmail.com,Ongoing,1.309357,1.609785,1.017651,-0.342767
250,251,Sita,Data Science,Biratnagar,20,Female,2026-01-19,7000,0,Pending,...,86,3,Manish,9837716287,user250@gmail.com,Completed,-0.133692,0.647345,1.599642,1.018274
251,252,Hari,Data Science,Pokhara,23,Male,2026-02-04,5000,10,Paid,...,69,3,Ishan,9853738211,user251@gmail.com,Completed,-1.095725,-1.036924,-0.146332,0.191927
258,259,Suman,Data Science,Pokhara,27,Male,2026-05-12,10000,0,Pending,...,31,4,Manish,9800428055,user258@gmail.com,Ongoing,1.309357,-0.014332,-1.601310,-1.655200
261,262,Gita,Data Science,Dharan,30,Female,2026-05-24,10000,10,Paid,...,44,5,Samriddha,9804258047,user261@gmail.com,Completed,1.309357,0.286430,-0.776822,-1.023288
266,267,Hari,Data Science,Kathmandu,25,Male,2026-05-01,7000,10,Paid,...,39,4,Ishan,9863080418,user266@gmail.com,Completed,-0.133692,1.669937,0.920652,-1.266331
282,283,Suman,Data Science,Itahari,28,Female,2026-04-16,10000,10,Paid,...,94,3,Ishan,9837905639,user282@gmail.com,Ongoing,1.309357,0.827802,-0.243330,1.407143
292,293,Sita,Data Science,Pokhara,18,Female,2026-03-16,7000,10,Pending,...,69,3,Ishan,9826303026,user292@gmail.com,Completed,-0.133692,-1.397839,1.405645,0.191927
298,299,Suman,Data Science,Dharan,34,Male,2026-01-06,7000,20,Paid,...,87,3,Manish,9865044701,user298@gmail.com,Completed,-0.133692,-0.194790,0.290162,1.066882
299,300,Anisha,Data Science,Kathmandu,17,Male,2026-06-27,7000,10,Pending,...,78,4,Samriddha,9868962770,user299@gmail.com,Ongoing,-0.133692,1.128565,-0.000834,0.629405
306,307,Nabin,Data Science,Itahari,17,Female,2026-04-03,5000,0,Pending,...,70,4,Manish,9825583895,user306@gmail.com,Ongoing,-1.095725,0.346583,-0.049333,0.240536
308,309,Suman,Data Science,Itahari,24,Female,2026-04-25,7000,20,Paid,...,85,4,Samriddha,9820668267,user308@gmail.com,Completed,-0.133692,-1.518144,-1.649809,0.969665
313,314,Suman,Data Science,Itahari,18,Female,2026-05-04,5000,10,Paid,...,33,3,Ishan,9850786193,user313@gmail.com,Ongoing,-1.095725,0.767650,-0.776822,-1.557983
323,324,Nabin,Data Science,Kathmandu,30,Female,2026-03-02,7000,10,Pending,...,78,5,Samriddha,9814934857,user323@gmail.com,Ongoing,-0.133692,-0.615857,1.551143,0.629405
324,325,Sita,Data Science,Pokhara,24,Male,2026-05-01,5000,20,Paid,...,41,4,Samriddha,9834163380,user324@gmail.com,Completed,-1.095725,-0.254942,-0.437327,-1.169114
325,326,Hari,Data Science,Dharan,32,Male,2026-06-20,10000,20,Paid,...,35,3,Manish,9839860825,user325@gmail.com,Completed,1.309357,-0.315095,-0.146332,-1.460765
327,328,Suman,Data Science,Pokhara,26,Male,2026-02-13,10000,0,Pending,...,82,5,Samriddha,9863078333,user327@gmail.com,Ongoing,1.309357,-1.818907,1.454144,0.823839
333,334,Gita,Data Science,Dharan,23,Male,2026-04-13,10000,10,Pending,...,55,5,Manish,9870900500,user333@gmail.com,Ongoing,1.309357,-1.217382,-1.746808,-0.488593
338,339,Hari,Data Science,Dharan,17,Male,2026-04-22,5000,10,Pending,...,93,3,Samriddha,9817310408,user338@gmail.com,Ongoing,-1.095725,-1.758754,1.163149,1.358534

In [48]:
d.groupby("course")["course_fee"].get_group("Data Science")

1      10000
4       5000
5       7000
16      7000
31     10000
34      5000
38     10000
46     10000
47      7000
55     10000
58      7000
61     10000
64      7000
69     10000
75      5000
81      5000
88      7000
93      7000
104    10000
118     5000
124    10000
136    10000
139     7000
142     7000
148     5000
154     7000
157     5000
167    10000
176    10000
180    10000
188     5000
196     5000
198     7000
199     7000
200     5000
201     5000
204    10000
213     7000
217     5000
219    10000
230     7000
238    10000
250     7000
251     5000
258    10000
261    10000
266     7000
282    10000
292     7000
298     7000
299     7000
306     5000
308     7000
313     5000
323     7000
324     5000
325    10000
327    10000
333    10000
338     5000
Name: course_fee, dtype: int64

In [49]:
d.groupby("course").agg({
    "course_fee":"min",
    "discount":"max"
    
    
})

                   course_fee  discount
course
Data Science             5000        20
Digital Marketing        5000        20
Flutter                  5000        20
Mern Stack               5000        20
Pythn Ai                 7000         0
Python With Ai/Ml        5000        20
Ui/Ux                    5000        20